var searchData=
[
  ['range_7988',['Range',['../classCDPL_1_1Math_1_1Range.html',1,'CDPL::Math']]],
  ['range_3c_20sizetype_20_3e_7989',['Range&lt; SizeType &gt;',['../classCDPL_1_1Math_1_1Range.html',1,'CDPL::Math']]],
  ['rangeerror_7990',['RangeError',['../classCDPL_1_1Base_1_1RangeError.html',1,'CDPL::Base']]],
  ['rdfcodecalculator_7991',['RDFCodeCalculator',['../classCDPL_1_1Descr_1_1RDFCodeCalculator.html',1,'CDPL::Descr']]],
  ['rdfcodecalculator_3c_20chem_3a_3aatom_20_3e_7992',['RDFCodeCalculator&lt; Chem::Atom &gt;',['../classCDPL_1_1Descr_1_1RDFCodeCalculator.html',1,'CDPL::Descr']]],
  ['rdfcodecalculator_3c_20pharm_3a_3afeature_20_3e_7993',['RDFCodeCalculator&lt; Pharm::Feature &gt;',['../classCDPL_1_1Descr_1_1RDFCodeCalculator.html',1,'CDPL::Descr']]],
  ['rdfreactionreader_7994',['RDFReactionReader',['../classCDPL_1_1Chem_1_1RDFReactionReader.html',1,'CDPL::Chem']]],
  ['rdfreactionwriter_7995',['RDFReactionWriter',['../classCDPL_1_1Chem_1_1RDFReactionWriter.html',1,'CDPL::Chem']]],
  ['reaction_7996',['Reaction',['../classCDPL_1_1Chem_1_1Reaction.html',1,'CDPL::Chem']]],
  ['reactionatommappingmatchexpression_7997',['ReactionAtomMappingMatchExpression',['../classCDPL_1_1Chem_1_1ReactionAtomMappingMatchExpression.html',1,'CDPL::Chem']]],
  ['reactioncomponentgroupingmatchexpression_7998',['ReactionComponentGroupingMatchExpression',['../classCDPL_1_1Chem_1_1ReactionComponentGroupingMatchExpression.html',1,'CDPL::Chem']]],
  ['reactionsubstructuresearch_7999',['ReactionSubstructureSearch',['../classCDPL_1_1Chem_1_1ReactionSubstructureSearch.html',1,'CDPL::Chem']]],
  ['reactionview2d_8000',['ReactionView2D',['../classCDPL_1_1Vis_1_1ReactionView2D.html',1,'CDPL::Vis']]],
  ['reactor_8001',['Reactor',['../classCDPL_1_1Chem_1_1Reactor.html',1,'CDPL::Chem']]],
  ['realquaternion_8002',['RealQuaternion',['../classCDPL_1_1Math_1_1RealQuaternion.html',1,'CDPL::Math']]],
  ['recapfragmentgenerator_8003',['RECAPFragmentGenerator',['../classCDPL_1_1Chem_1_1RECAPFragmentGenerator.html',1,'CDPL::Chem']]],
  ['rectangle2d_8004',['Rectangle2D',['../classCDPL_1_1Vis_1_1Rectangle2D.html',1,'CDPL::Vis']]],
  ['referencecolortverskyscore_8005',['ReferenceColorTverskyScore',['../classCDPL_1_1Shape_1_1ReferenceColorTverskyScore.html',1,'CDPL::Shape']]],
  ['referenceshapetverskyscore_8006',['ReferenceShapeTverskyScore',['../classCDPL_1_1Shape_1_1ReferenceShapeTverskyScore.html',1,'CDPL::Shape']]],
  ['referencetotaloverlaptverskyscore_8007',['ReferenceTotalOverlapTverskyScore',['../classCDPL_1_1Shape_1_1ReferenceTotalOverlapTverskyScore.html',1,'CDPL::Shape']]],
  ['referencetverskycomboscore_8008',['ReferenceTverskyComboScore',['../classCDPL_1_1Shape_1_1ReferenceTverskyComboScore.html',1,'CDPL::Shape']]],
  ['regulargrid_8009',['RegularGrid',['../classCDPL_1_1Grid_1_1RegularGrid.html',1,'CDPL::Grid']]],
  ['regulargridset_8010',['RegularGridSet',['../classCDPL_1_1Grid_1_1RegularGridSet.html',1,'CDPL::Grid']]],
  ['regularspatialgrid_8011',['RegularSpatialGrid',['../classCDPL_1_1Math_1_1RegularSpatialGrid.html',1,'CDPL::Math']]],
  ['renderer2d_8012',['Renderer2D',['../classCDPL_1_1Vis_1_1Renderer2D.html',1,'CDPL::Vis']]],
  ['residuedictionary_8013',['ResidueDictionary',['../classCDPL_1_1Biomol_1_1ResidueDictionary.html',1,'CDPL::Biomol']]],
  ['residuelist_8014',['ResidueList',['../classCDPL_1_1Biomol_1_1ResidueList.html',1,'CDPL::Biomol']]],
  ['resonancestructuregenerator_8015',['ResonanceStructureGenerator',['../classCDPL_1_1Chem_1_1ResonanceStructureGenerator.html',1,'CDPL::Chem']]],
  ['result_8016',['Result',['../classCDPL_1_1Shape_1_1GaussianShapeFunctionAlignment_1_1Result.html',1,'CDPL::Shape::GaussianShapeFunctionAlignment']]],
  ['rmsdconformerselector_8017',['RMSDConformerSelector',['../classCDPL_1_1ConfGen_1_1RMSDConformerSelector.html',1,'CDPL::ConfGen']]],
  ['rotationmatrix_8018',['RotationMatrix',['../classCDPL_1_1Math_1_1RotationMatrix.html',1,'CDPL::Math']]],
  ['rxnreactionreader_8019',['RXNReactionReader',['../classCDPL_1_1Chem_1_1RXNReactionReader.html',1,'CDPL::Chem']]],
  ['rxnreactionwriter_8020',['RXNReactionWriter',['../classCDPL_1_1Chem_1_1RXNReactionWriter.html',1,'CDPL::Chem']]]
];
