var searchData=
[
  ['range_7786',['Range',['../classCDPL_1_1Math_1_1Range.html',1,'CDPL::Math']]],
  ['range_3c_20sizetype_20_3e_7787',['Range&lt; SizeType &gt;',['../classCDPL_1_1Math_1_1Range.html',1,'CDPL::Math']]],
  ['rangeerror_7788',['RangeError',['../classCDPL_1_1Base_1_1RangeError.html',1,'CDPL::Base']]],
  ['rdfcodecalculator_7789',['RDFCodeCalculator',['../classCDPL_1_1Descr_1_1RDFCodeCalculator.html',1,'CDPL::Descr']]],
  ['rdfcodecalculator_3c_20chem_3a_3aatom_20_3e_7790',['RDFCodeCalculator&lt; Chem::Atom &gt;',['../classCDPL_1_1Descr_1_1RDFCodeCalculator.html',1,'CDPL::Descr']]],
  ['rdfcodecalculator_3c_20pharm_3a_3afeature_20_3e_7791',['RDFCodeCalculator&lt; Pharm::Feature &gt;',['../classCDPL_1_1Descr_1_1RDFCodeCalculator.html',1,'CDPL::Descr']]],
  ['rdfreactionreader_7792',['RDFReactionReader',['../classCDPL_1_1Chem_1_1RDFReactionReader.html',1,'CDPL::Chem']]],
  ['rdfreactionwriter_7793',['RDFReactionWriter',['../classCDPL_1_1Chem_1_1RDFReactionWriter.html',1,'CDPL::Chem']]],
  ['reaction_7794',['Reaction',['../classCDPL_1_1Chem_1_1Reaction.html',1,'CDPL::Chem']]],
  ['reactionatommappingmatchexpression_7795',['ReactionAtomMappingMatchExpression',['../classCDPL_1_1Chem_1_1ReactionAtomMappingMatchExpression.html',1,'CDPL::Chem']]],
  ['reactioncomponentgroupingmatchexpression_7796',['ReactionComponentGroupingMatchExpression',['../classCDPL_1_1Chem_1_1ReactionComponentGroupingMatchExpression.html',1,'CDPL::Chem']]],
  ['reactionsubstructuresearch_7797',['ReactionSubstructureSearch',['../classCDPL_1_1Chem_1_1ReactionSubstructureSearch.html',1,'CDPL::Chem']]],
  ['reactionview2d_7798',['ReactionView2D',['../classCDPL_1_1Vis_1_1ReactionView2D.html',1,'CDPL::Vis']]],
  ['reactor_7799',['Reactor',['../classCDPL_1_1Chem_1_1Reactor.html',1,'CDPL::Chem']]],
  ['realquaternion_7800',['RealQuaternion',['../classCDPL_1_1Math_1_1RealQuaternion.html',1,'CDPL::Math']]],
  ['recapfragmentgenerator_7801',['RECAPFragmentGenerator',['../classCDPL_1_1Chem_1_1RECAPFragmentGenerator.html',1,'CDPL::Chem']]],
  ['rectangle2d_7802',['Rectangle2D',['../classCDPL_1_1Vis_1_1Rectangle2D.html',1,'CDPL::Vis']]],
  ['referencecolortverskyscore_7803',['ReferenceColorTverskyScore',['../classCDPL_1_1Shape_1_1ReferenceColorTverskyScore.html',1,'CDPL::Shape']]],
  ['referenceshapetverskyscore_7804',['ReferenceShapeTverskyScore',['../classCDPL_1_1Shape_1_1ReferenceShapeTverskyScore.html',1,'CDPL::Shape']]],
  ['referencetotaloverlaptverskyscore_7805',['ReferenceTotalOverlapTverskyScore',['../classCDPL_1_1Shape_1_1ReferenceTotalOverlapTverskyScore.html',1,'CDPL::Shape']]],
  ['referencetverskycomboscore_7806',['ReferenceTverskyComboScore',['../classCDPL_1_1Shape_1_1ReferenceTverskyComboScore.html',1,'CDPL::Shape']]],
  ['regulargrid_7807',['RegularGrid',['../classCDPL_1_1Grid_1_1RegularGrid.html',1,'CDPL::Grid']]],
  ['regulargridset_7808',['RegularGridSet',['../classCDPL_1_1Grid_1_1RegularGridSet.html',1,'CDPL::Grid']]],
  ['regularspatialgrid_7809',['RegularSpatialGrid',['../classCDPL_1_1Math_1_1RegularSpatialGrid.html',1,'CDPL::Math']]],
  ['renderer2d_7810',['Renderer2D',['../classCDPL_1_1Vis_1_1Renderer2D.html',1,'CDPL::Vis']]],
  ['residuedictionary_7811',['ResidueDictionary',['../classCDPL_1_1Biomol_1_1ResidueDictionary.html',1,'CDPL::Biomol']]],
  ['residuelist_7812',['ResidueList',['../classCDPL_1_1Biomol_1_1ResidueList.html',1,'CDPL::Biomol']]],
  ['resonancestructuregenerator_7813',['ResonanceStructureGenerator',['../classCDPL_1_1Chem_1_1ResonanceStructureGenerator.html',1,'CDPL::Chem']]],
  ['result_7814',['Result',['../classCDPL_1_1Shape_1_1GaussianShapeFunctionAlignment_1_1Result.html',1,'CDPL::Shape::GaussianShapeFunctionAlignment']]],
  ['rmsdconformerselector_7815',['RMSDConformerSelector',['../classCDPL_1_1ConfGen_1_1RMSDConformerSelector.html',1,'CDPL::ConfGen']]],
  ['rotationmatrix_7816',['RotationMatrix',['../classCDPL_1_1Math_1_1RotationMatrix.html',1,'CDPL::Math']]],
  ['rxnreactionreader_7817',['RXNReactionReader',['../classCDPL_1_1Chem_1_1RXNReactionReader.html',1,'CDPL::Chem']]],
  ['rxnreactionwriter_7818',['RXNReactionWriter',['../classCDPL_1_1Chem_1_1RXNReactionWriter.html',1,'CDPL::Chem']]]
];
