var searchData=
[
  ['range_8377',['Range',['../classCDPL_1_1Math_1_1Range.html',1,'CDPL::Math']]],
  ['range_3c_20sizetype_20_3e_8378',['Range&lt; SizeType &gt;',['../classCDPL_1_1Math_1_1Range.html',1,'CDPL::Math']]],
  ['rangeerror_8379',['RangeError',['../classCDPL_1_1Base_1_1RangeError.html',1,'CDPL::Base']]],
  ['rdfcodecalculator_8380',['RDFCodeCalculator',['../classCDPL_1_1Descr_1_1RDFCodeCalculator.html',1,'CDPL::Descr']]],
  ['rdfcodecalculator_3c_20chem_3a_3aatom_20_3e_8381',['RDFCodeCalculator&lt; Chem::Atom &gt;',['../classCDPL_1_1Descr_1_1RDFCodeCalculator.html',1,'CDPL::Descr']]],
  ['rdfcodecalculator_3c_20pharm_3a_3afeature_20_3e_8382',['RDFCodeCalculator&lt; Pharm::Feature &gt;',['../classCDPL_1_1Descr_1_1RDFCodeCalculator.html',1,'CDPL::Descr']]],
  ['rdfreactionreader_8383',['RDFReactionReader',['../classCDPL_1_1Chem_1_1RDFReactionReader.html',1,'CDPL::Chem']]],
  ['rdfreactionwriter_8384',['RDFReactionWriter',['../classCDPL_1_1Chem_1_1RDFReactionWriter.html',1,'CDPL::Chem']]],
  ['reaction_8385',['Reaction',['../classCDPL_1_1Chem_1_1Reaction.html',1,'CDPL::Chem']]],
  ['reactionatommappingmatchexpression_8386',['ReactionAtomMappingMatchExpression',['../classCDPL_1_1Chem_1_1ReactionAtomMappingMatchExpression.html',1,'CDPL::Chem']]],
  ['reactioncomponentgroupingmatchexpression_8387',['ReactionComponentGroupingMatchExpression',['../classCDPL_1_1Chem_1_1ReactionComponentGroupingMatchExpression.html',1,'CDPL::Chem']]],
  ['reactionsubstructuresearch_8388',['ReactionSubstructureSearch',['../classCDPL_1_1Chem_1_1ReactionSubstructureSearch.html',1,'CDPL::Chem']]],
  ['reactionview2d_8389',['ReactionView2D',['../classCDPL_1_1Vis_1_1ReactionView2D.html',1,'CDPL::Vis']]],
  ['reactor_8390',['Reactor',['../classCDPL_1_1Chem_1_1Reactor.html',1,'CDPL::Chem']]],
  ['realquaternion_8391',['RealQuaternion',['../classCDPL_1_1Math_1_1RealQuaternion.html',1,'CDPL::Math']]],
  ['recapfragmentgenerator_8392',['RECAPFragmentGenerator',['../classCDPL_1_1Chem_1_1RECAPFragmentGenerator.html',1,'CDPL::Chem']]],
  ['rectangle2d_8393',['Rectangle2D',['../classCDPL_1_1Vis_1_1Rectangle2D.html',1,'CDPL::Vis']]],
  ['referencecolortverskyscore_8394',['ReferenceColorTverskyScore',['../classCDPL_1_1Shape_1_1ReferenceColorTverskyScore.html',1,'CDPL::Shape']]],
  ['referenceshapetverskyscore_8395',['ReferenceShapeTverskyScore',['../classCDPL_1_1Shape_1_1ReferenceShapeTverskyScore.html',1,'CDPL::Shape']]],
  ['referencetotaloverlaptverskyscore_8396',['ReferenceTotalOverlapTverskyScore',['../classCDPL_1_1Shape_1_1ReferenceTotalOverlapTverskyScore.html',1,'CDPL::Shape']]],
  ['referencetverskycomboscore_8397',['ReferenceTverskyComboScore',['../classCDPL_1_1Shape_1_1ReferenceTverskyComboScore.html',1,'CDPL::Shape']]],
  ['regulargrid_8398',['RegularGrid',['../classCDPL_1_1Grid_1_1RegularGrid.html',1,'CDPL::Grid']]],
  ['regulargridset_8399',['RegularGridSet',['../classCDPL_1_1Grid_1_1RegularGridSet.html',1,'CDPL::Grid']]],
  ['regularspatialgrid_8400',['RegularSpatialGrid',['../classCDPL_1_1Math_1_1RegularSpatialGrid.html',1,'CDPL::Math']]],
  ['regularspatialgrid_3c_20t_2c_20t_20_3e_8401',['RegularSpatialGrid&lt; T, T &gt;',['../classCDPL_1_1Math_1_1RegularSpatialGrid.html',1,'CDPL::Math']]],
  ['renderer2d_8402',['Renderer2D',['../classCDPL_1_1Vis_1_1Renderer2D.html',1,'CDPL::Vis']]],
  ['residuedictionary_8403',['ResidueDictionary',['../classCDPL_1_1Biomol_1_1ResidueDictionary.html',1,'CDPL::Biomol']]],
  ['residuelist_8404',['ResidueList',['../classCDPL_1_1Biomol_1_1ResidueList.html',1,'CDPL::Biomol']]],
  ['resonancestructuregenerator_8405',['ResonanceStructureGenerator',['../classCDPL_1_1Chem_1_1ResonanceStructureGenerator.html',1,'CDPL::Chem']]],
  ['result_8406',['Result',['../classCDPL_1_1Shape_1_1GaussianShapeFunctionAlignment_1_1Result.html',1,'CDPL::Shape::GaussianShapeFunctionAlignment']]],
  ['rmsdconformerselector_8407',['RMSDConformerSelector',['../classCDPL_1_1ConfGen_1_1RMSDConformerSelector.html',1,'CDPL::ConfGen']]],
  ['rotationmatrix_8408',['RotationMatrix',['../classCDPL_1_1Math_1_1RotationMatrix.html',1,'CDPL::Math']]],
  ['rxnreactionreader_8409',['RXNReactionReader',['../classCDPL_1_1Chem_1_1RXNReactionReader.html',1,'CDPL::Chem']]],
  ['rxnreactionwriter_8410',['RXNReactionWriter',['../classCDPL_1_1Chem_1_1RXNReactionWriter.html',1,'CDPL::Chem']]]
];
