var searchData=
[
  ['range_8376',['Range',['../classCDPL_1_1Math_1_1Range.html',1,'CDPL::Math']]],
  ['range_3c_20sizetype_20_3e_8377',['Range&lt; SizeType &gt;',['../classCDPL_1_1Math_1_1Range.html',1,'CDPL::Math']]],
  ['rangeerror_8378',['RangeError',['../classCDPL_1_1Base_1_1RangeError.html',1,'CDPL::Base']]],
  ['rdfcodecalculator_8379',['RDFCodeCalculator',['../classCDPL_1_1Descr_1_1RDFCodeCalculator.html',1,'CDPL::Descr']]],
  ['rdfcodecalculator_3c_20chem_3a_3aatom_20_3e_8380',['RDFCodeCalculator&lt; Chem::Atom &gt;',['../classCDPL_1_1Descr_1_1RDFCodeCalculator.html',1,'CDPL::Descr']]],
  ['rdfcodecalculator_3c_20pharm_3a_3afeature_20_3e_8381',['RDFCodeCalculator&lt; Pharm::Feature &gt;',['../classCDPL_1_1Descr_1_1RDFCodeCalculator.html',1,'CDPL::Descr']]],
  ['rdfreactionreader_8382',['RDFReactionReader',['../classCDPL_1_1Chem_1_1RDFReactionReader.html',1,'CDPL::Chem']]],
  ['rdfreactionwriter_8383',['RDFReactionWriter',['../classCDPL_1_1Chem_1_1RDFReactionWriter.html',1,'CDPL::Chem']]],
  ['reaction_8384',['Reaction',['../classCDPL_1_1Chem_1_1Reaction.html',1,'CDPL::Chem']]],
  ['reactionatommappingmatchexpression_8385',['ReactionAtomMappingMatchExpression',['../classCDPL_1_1Chem_1_1ReactionAtomMappingMatchExpression.html',1,'CDPL::Chem']]],
  ['reactioncomponentgroupingmatchexpression_8386',['ReactionComponentGroupingMatchExpression',['../classCDPL_1_1Chem_1_1ReactionComponentGroupingMatchExpression.html',1,'CDPL::Chem']]],
  ['reactionsubstructuresearch_8387',['ReactionSubstructureSearch',['../classCDPL_1_1Chem_1_1ReactionSubstructureSearch.html',1,'CDPL::Chem']]],
  ['reactionview2d_8388',['ReactionView2D',['../classCDPL_1_1Vis_1_1ReactionView2D.html',1,'CDPL::Vis']]],
  ['reactor_8389',['Reactor',['../classCDPL_1_1Chem_1_1Reactor.html',1,'CDPL::Chem']]],
  ['realquaternion_8390',['RealQuaternion',['../classCDPL_1_1Math_1_1RealQuaternion.html',1,'CDPL::Math']]],
  ['recapfragmentgenerator_8391',['RECAPFragmentGenerator',['../classCDPL_1_1Chem_1_1RECAPFragmentGenerator.html',1,'CDPL::Chem']]],
  ['rectangle2d_8392',['Rectangle2D',['../classCDPL_1_1Vis_1_1Rectangle2D.html',1,'CDPL::Vis']]],
  ['referencecolortverskyscore_8393',['ReferenceColorTverskyScore',['../classCDPL_1_1Shape_1_1ReferenceColorTverskyScore.html',1,'CDPL::Shape']]],
  ['referenceshapetverskyscore_8394',['ReferenceShapeTverskyScore',['../classCDPL_1_1Shape_1_1ReferenceShapeTverskyScore.html',1,'CDPL::Shape']]],
  ['referencetotaloverlaptverskyscore_8395',['ReferenceTotalOverlapTverskyScore',['../classCDPL_1_1Shape_1_1ReferenceTotalOverlapTverskyScore.html',1,'CDPL::Shape']]],
  ['referencetverskycomboscore_8396',['ReferenceTverskyComboScore',['../classCDPL_1_1Shape_1_1ReferenceTverskyComboScore.html',1,'CDPL::Shape']]],
  ['regulargrid_8397',['RegularGrid',['../classCDPL_1_1Grid_1_1RegularGrid.html',1,'CDPL::Grid']]],
  ['regulargridset_8398',['RegularGridSet',['../classCDPL_1_1Grid_1_1RegularGridSet.html',1,'CDPL::Grid']]],
  ['regularspatialgrid_8399',['RegularSpatialGrid',['../classCDPL_1_1Math_1_1RegularSpatialGrid.html',1,'CDPL::Math']]],
  ['regularspatialgrid_3c_20t_2c_20t_20_3e_8400',['RegularSpatialGrid&lt; T, T &gt;',['../classCDPL_1_1Math_1_1RegularSpatialGrid.html',1,'CDPL::Math']]],
  ['renderer2d_8401',['Renderer2D',['../classCDPL_1_1Vis_1_1Renderer2D.html',1,'CDPL::Vis']]],
  ['residuedictionary_8402',['ResidueDictionary',['../classCDPL_1_1Biomol_1_1ResidueDictionary.html',1,'CDPL::Biomol']]],
  ['residuelist_8403',['ResidueList',['../classCDPL_1_1Biomol_1_1ResidueList.html',1,'CDPL::Biomol']]],
  ['resonancestructuregenerator_8404',['ResonanceStructureGenerator',['../classCDPL_1_1Chem_1_1ResonanceStructureGenerator.html',1,'CDPL::Chem']]],
  ['result_8405',['Result',['../classCDPL_1_1Shape_1_1GaussianShapeFunctionAlignment_1_1Result.html',1,'CDPL::Shape::GaussianShapeFunctionAlignment']]],
  ['rmsdconformerselector_8406',['RMSDConformerSelector',['../classCDPL_1_1ConfGen_1_1RMSDConformerSelector.html',1,'CDPL::ConfGen']]],
  ['rotationmatrix_8407',['RotationMatrix',['../classCDPL_1_1Math_1_1RotationMatrix.html',1,'CDPL::Math']]],
  ['rxnreactionreader_8408',['RXNReactionReader',['../classCDPL_1_1Chem_1_1RXNReactionReader.html',1,'CDPL::Chem']]],
  ['rxnreactionwriter_8409',['RXNReactionWriter',['../classCDPL_1_1Chem_1_1RXNReactionWriter.html',1,'CDPL::Chem']]]
];
